### ISSUE TITLE
时间显示有点小问题

### ISSUE THREAD

**Issue by PacmanSun** [enria/Wox.Plugin.SSJ#3]
记录的时间是12小时制的，而且没有am,pm的区分。
请改为24小时制，那样更加直观。

**Comment by enria** [comment]
1. 关闭Wox（可能无法退出，需要到任务管理器中杀掉进程）
2. [下载更新](https://github.com/enria/Wox.Plugin.SSJ/releases/download/1.0.1/Wox.Plugin.SSJ.dll)，放到插件文件夹中替换，插件文件夹为`C:\Users\xxx\AppData\Roaming\Wox\Plugins\随手记-xxx`
3. 重启Wox

**Comment by enria** [comment]
是一个Bug，已经修复了。
